package com.springapp.mvc.dao;

import com.springapp.mvc.model.Tuser;

public interface TuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    Tuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Mar 15 17:15:28 CST 2016
     */
    int updateByPrimaryKey(Tuser record);
}